/**
 * Generated by Scrooge
 *   version: 4.18.0
 *   rev: 19f0c3c1e92bca00860d6b0b3c7edea6702ab439
 *   built at: 20170609-100323
 */
package thrift

import com.twitter.io.Buf
import com.twitter.scrooge.{
  HasThriftStructCodec3,
  LazyTProtocol,
  TFieldBlob,
  ThriftException,
  ThriftStruct,
  ThriftStructCodec3,
  ThriftStructFieldInfo,
  ThriftStructMetaData,
  ThriftUtil
}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{ TMemoryBuffer, TTransport, TIOStreamTransport }
import java.io.ByteArrayInputStream
import java.nio.ByteBuffer
import java.util.Arrays
import java.util.concurrent.atomic.AtomicInteger
import scala.collection.immutable.{ Map => immutable$Map }
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer,
  Buffer => mutable$Buffer,
  HashMap => mutable$HashMap,
  HashSet => mutable$HashSet
}
import scala.collection.{ Map, Set }

object Work extends ThriftStructCodec3[Work] {
  val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("Work")
  val OpField = new TField("op", TType.ENUM, 1)
  val OpFieldI32 = new TField("op", TType.I32, 1)
  val OpFieldManifest = implicitly[Manifest[thrift.Operation]]
  val StatusField = new TField("status", TType.I32, 2)
  val StatusFieldManifest = implicitly[Manifest[Int]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      OpField,
      false,
      true,
      OpFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None),
    new ThriftStructFieldInfo(
      StatusField,
      true,
      false,
      StatusFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None))

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: Work): Unit = {
    if (_item.op == null) throw new TProtocolException("Required field op cannot be null")
  }

  def withoutPassthroughFields(original: Work): Work =
    new Immutable(
      op =
        {
          val field = original.op
          field
        },
      status =
        {
          val field = original.status
          field.map { field =>
            field
          }
        })

  override def encode(_item: Work, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): Work = {

    var op: thrift.Operation = null
    var _got_op = false
    var statusOffset: Int = -1

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>

                op = readOpValue(_iprot)
                _got_op = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'op' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)))
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 =>
                statusOffset = _iprot.offsetSkipI32

              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'status' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)))
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_op) throw new TProtocolException("Required field 'op' was not found in serialized data for struct Work")
    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      op,
      statusOffset,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result())
  }

  override def decode(_iprot: TProtocol): Work =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[thrift] def eagerDecode(_iprot: TProtocol): Work = {
    var op: thrift.Operation = null
    var _got_op = false
    var status: _root_.scala.Option[Int] = _root_.scala.None
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
                op = readOpValue(_iprot)
                _got_op = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'op' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)))
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 =>
                status = _root_.scala.Some(readStatusValue(_iprot))
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'status' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)))
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_op) throw new TProtocolException("Required field 'op' was not found in serialized data for struct Work")
    new Immutable(
      op,
      status,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result())
  }

  def apply(
    op: thrift.Operation,
    status: _root_.scala.Option[Int] = _root_.scala.None): Work =
    new Immutable(
      op,
      status)

  def unapply(_item: Work): _root_.scala.Option[_root_.scala.Tuple2[thrift.Operation, Option[Int]]] = _root_.scala.Some(_item.toTuple)

  @inline private[thrift] def readOpValue(_iprot: TProtocol): thrift.Operation = {
    thrift.Operation.getOrUnknown(_iprot.readI32())
  }

  @inline private def writeOpField(op_item: thrift.Operation, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(OpFieldI32)
    writeOpValue(op_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeOpValue(op_item: thrift.Operation, _oprot: TProtocol): Unit = {
    _oprot.writeI32(op_item.value)
  }

  @inline private[thrift] def readStatusValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeStatusField(status_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(StatusField)
    writeStatusValue(status_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeStatusValue(status_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(status_item)
  }

  object Immutable extends ThriftStructCodec3[Work] {
    override def encode(_item: Work, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): Work = Work.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[Work] = Work.metaData
  }

  /**
   * The default read-only implementation of Work.  You typically should not need to
   * directly reference this class; instead, use the Work.apply method to construct
   * new instances.
   */
  class Immutable(
    val op: thrift.Operation,
    val status: _root_.scala.Option[Int],
    override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends Work {
    def this(
      op: thrift.Operation,
      status: _root_.scala.Option[Int] = _root_.scala.None) = this(
      op,
      status,
      Map.empty)
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
    _proto: LazyTProtocol,
    _buf: Array[Byte],
    _start_offset: Int,
    _end_offset: Int,
    val op: thrift.Operation,
    statusOffset: Int,
    override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends Work {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val status: _root_.scala.Option[Int] =
      if (statusOffset == -1)
        None
      else {
        Some(_proto.decodeI32(_buf, statusOffset))
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the Work trait with additional state or
   * behavior and implement the read-only methods from Work using an underlying
   * instance.
   */
  trait Proxy extends Work {
    protected def _underlying_Work: Work
    override def op: thrift.Operation = _underlying_Work.op
    override def status: _root_.scala.Option[Int] = _underlying_Work.status
    override def _passthroughFields = _underlying_Work._passthroughFields
  }
}

/**
 * Prefer the companion object's [[thrift.Work.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
trait Work
  extends ThriftStruct
  with _root_.scala.Product2[thrift.Operation, Option[Int]]
  with HasThriftStructCodec3[Work]
  with java.io.Serializable {
  import Work._

  def op: thrift.Operation
  def status: _root_.scala.Option[Int]

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = op
  def _2 = status

  def toTuple: _root_.scala.Tuple2[thrift.Operation, Option[Int]] = {
    (
      op,
      status)
  }

  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (op ne null) {
                writeOpValue(op, _oprot)
                _root_.scala.Some(Work.OpField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (status.isDefined) {
                writeStatusValue(status.get, _oprot)
                _root_.scala.Some(Work.StatusField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): Work = {
    var op: thrift.Operation = this.op
    var status: _root_.scala.Option[Int] = this.status
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        op = readOpValue(_blob.read)
      case 2 =>
        status = _root_.scala.Some(readStatusValue(_blob.read))
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      op,
      status,
      _passthroughFields)
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): Work = {
    var op: thrift.Operation = this.op
    var status: _root_.scala.Option[Int] = this.status

    _fieldId match {
      case 1 =>
        op = null
      case 2 =>
        status = _root_.scala.None
      case _ =>
    }
    new Immutable(
      op,
      status,
      _passthroughFields - _fieldId)
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetOp: Work = unsetField(1)

  def unsetStatus: Work = unsetField(2)

  override def write(_oprot: TProtocol): Unit = {
    Work.validate(this)
    _oprot.writeStructBegin(Struct)
    if (op ne null) writeOpField(op, _oprot)
    if (status.isDefined) writeStatusField(status.get, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    op: thrift.Operation = this.op,
    status: _root_.scala.Option[Int] = this.status,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields): Work =
    new Immutable(
      op,
      status,
      _passthroughFields)

  override def canEqual(other: Any): Boolean = other.isInstanceOf[Work]

  private def _equals(x: Work, y: Work): Boolean =
    x.productArity == y.productArity &&
      x.productIterator.sameElements(y.productIterator)

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _equals(this, other.asInstanceOf[Work]) &&
      _passthroughFields == other.asInstanceOf[Work]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)

  override def productArity: Int = 2

  override def productElement(n: Int): Any = n match {
    case 0 => this.op
    case 1 => this.status
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "Work"

  def _codec: ThriftStructCodec3[Work] = Work
}

