/**
 * Generated by Scrooge
 *   version: 4.18.0
 *   rev: 19f0c3c1e92bca00860d6b0b3c7edea6702ab439
 *   built at: 20170609-100323
 */
package thrift

import com.twitter.finagle.SourcedException
import com.twitter.finagle.{ service => ctfs }
import com.twitter.finagle.stats.{ NullStatsReceiver, StatsReceiver }
import com.twitter.finagle.thrift.{ Protocols, ThriftClientRequest }
import com.twitter.scrooge.{ TReusableBuffer, ThriftStruct, ThriftStructCodec }
import com.twitter.util.{ Future, Return, Throw, Throwables }
import java.nio.ByteBuffer
import java.util.Arrays
import org.apache.thrift.protocol._
import org.apache.thrift.TApplicationException
import org.apache.thrift.transport.TMemoryInputTransport
import scala.collection.{ Map, Set }
import scala.language.higherKinds

@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
class WorkService$FinagleClient(
  val service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
  val protocolFactory: TProtocolFactory,
  val serviceName: String,
  stats: StatsReceiver,
  responseClassifier: ctfs.ResponseClassifier)
  extends WorkService[Future] {

  def this(
    service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
    protocolFactory: TProtocolFactory = Protocols.binaryFactory(),
    serviceName: String = "WorkService",
    stats: StatsReceiver = NullStatsReceiver) = this(
    service,
    protocolFactory,
    serviceName,
    stats,
    ctfs.ResponseClassifier.Default)

  import WorkService._

  private[this] val tlReusableBuffer = TReusableBuffer()

  protected def encodeRequest(name: String, args: ThriftStruct) = {
    val memoryBuffer = tlReusableBuffer.get()
    try {
      val oprot = protocolFactory.getProtocol(memoryBuffer)

      oprot.writeMessageBegin(new TMessage(name, TMessageType.CALL, 0))
      args.write(oprot)
      oprot.writeMessageEnd()
      oprot.getTransport().flush()
      val bytes = Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length())
      new ThriftClientRequest(bytes, false)
    } finally {
      tlReusableBuffer.reset()
    }
  }

  protected def decodeResponse[T <: ThriftStruct](resBytes: Array[Byte], codec: ThriftStructCodec[T]) = {
    val iprot = protocolFactory.getProtocol(new TMemoryInputTransport(resBytes))
    val msg = iprot.readMessageBegin()
    try {
      if (msg.`type` == TMessageType.EXCEPTION) {
        val exception = TApplicationException.read(iprot) match {
          case sourced: SourcedException =>
            if (serviceName != "") sourced.serviceName = serviceName
            sourced
          case e => e
        }
        throw exception
      } else {
        codec.decode(iprot)
      }
    } finally {
      iprot.readMessageEnd()
    }
  }

  protected def missingResult(name: String) = {
    new TApplicationException(
      TApplicationException.MISSING_RESULT,
      name + " failed: unknown result")
  }

  protected def setServiceName(ex: Throwable): Throwable =
    if (this.serviceName == "") ex
    else {
      ex match {
        case se: SourcedException =>
          se.serviceName = this.serviceName
          se
        case _ => ex
      }
    }

  // ----- end boilerplate.

  private[this] val scopedStats = if (serviceName != "") stats.scope(serviceName) else stats
  private[this] object __stats_findOperationList {
    val RequestsCounter = scopedStats.scope("findOperationList").counter("requests")
    val SuccessCounter = scopedStats.scope("findOperationList").counter("success")
    val FailuresCounter = scopedStats.scope("findOperationList").counter("failures")
    val FailuresScope = scopedStats.scope("findOperationList").scope("failures")
  }

  def findOperationList(): Future[Seq[thrift.Operation]] = {
    __stats_findOperationList.RequestsCounter.incr()
    val inputArgs = FindOperationList.Args()
    val replyDeserializer: Array[Byte] => _root_.com.twitter.util.Try[Seq[thrift.Operation]] =
      response => {
        val result = decodeResponse(response, FindOperationList.Result)
        val exception: Throwable =
          null

        if (result.success.isDefined)
          _root_.com.twitter.util.Return(result.success.get)
        else if (exception != null)
          _root_.com.twitter.util.Throw(exception)
        else
          _root_.com.twitter.util.Throw(missingResult("findOperationList"))
      }

    val serdeCtx = new _root_.com.twitter.finagle.thrift.DeserializeCtx[Seq[thrift.Operation]](inputArgs, replyDeserializer)
    _root_.com.twitter.finagle.context.Contexts.local.let(
      _root_.com.twitter.finagle.thrift.DeserializeCtx.Key,
      serdeCtx) {
        val serialized = encodeRequest("findOperationList", inputArgs)
        this.service(serialized).flatMap { response =>
          Future.const(serdeCtx.deserialize(response))
        }.respond { response =>
          val responseClass = responseClassifier.applyOrElse(
            ctfs.ReqRep(inputArgs, response),
            ctfs.ResponseClassifier.Default)
          responseClass match {
            case ctfs.ResponseClass.Successful(_) =>
              __stats_findOperationList.SuccessCounter.incr()
            case ctfs.ResponseClass.Failed(_) =>
              __stats_findOperationList.FailuresCounter.incr()
              response match {
                case Throw(ex) =>
                  setServiceName(ex)
                  __stats_findOperationList.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
                case _ =>
              }
          }
        }
      }
  }
}
