/**
 * Generated by Scrooge
 *   version: 4.18.0
 *   rev: 19f0c3c1e92bca00860d6b0b3c7edea6702ab439
 *   built at: 20170609-100323
 */
package thrift

import com.twitter.scrooge.{
  LazyTProtocol,
  HasThriftStructCodec3,
  TFieldBlob,
  ThriftService,
  ThriftStruct,
  ThriftStructCodec,
  ThriftStructCodec3,
  ThriftStructFieldInfo,
  ThriftResponse,
  ThriftUtil,
  ToThriftService
}
import com.twitter.finagle.{ service => ctfs }
import com.twitter.finagle.thrift.{ Protocols, ThriftClientRequest, ThriftServiceIface }
import com.twitter.util.Future
import java.nio.ByteBuffer
import java.util.Arrays
import org.apache.thrift.protocol._
import org.apache.thrift.transport.TTransport
import org.apache.thrift.TApplicationException
import org.apache.thrift.transport.TMemoryBuffer
import scala.collection.immutable.{ Map => immutable$Map }
import scala.collection.mutable.{
  Builder,
  ArrayBuffer => mutable$ArrayBuffer,
  Buffer => mutable$Buffer,
  HashMap => mutable$HashMap,
  HashSet => mutable$HashSet
}
import scala.collection.{ Map, Set }
import scala.language.higherKinds

@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
trait WorkService[+MM[_]] extends ThriftService {

  def findOperationList(): MM[Seq[thrift.Operation]]
}

object WorkService { self =>

  val annotations: immutable$Map[String, String] = immutable$Map.empty

  trait BaseServiceIface extends ToThriftService {
    def findOperationList: com.twitter.finagle.Service[self.FindOperationList.Args, self.FindOperationList.SuccessType]

    def toThriftService: ThriftService = new MethodIface(this)
  }

  case class ServiceIface(
    findOperationList: com.twitter.finagle.Service[self.FindOperationList.Args, self.FindOperationList.SuccessType]) extends BaseServiceIface
    with com.twitter.finagle.thrift.ThriftServiceIface.Filterable[ServiceIface] {

    /**
     * Prepends the given type-agnostic `Filter` to all of the `Services`
     * and returns a copy of the `ServiceIface` now including the filter.
     */
    def filtered(filter: com.twitter.finagle.Filter.TypeAgnostic): ServiceIface =
      copy(
        findOperationList = filter.toFilter.andThen(findOperationList))
  }

  implicit object ServiceIfaceBuilder
    extends com.twitter.finagle.thrift.ServiceIfaceBuilder[ServiceIface] {
    def newServiceIface(
      binaryService: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
      pf: TProtocolFactory = com.twitter.finagle.thrift.Protocols.binaryFactory(),
      stats: com.twitter.finagle.stats.StatsReceiver,
      responseClassifier: ctfs.ResponseClassifier = ctfs.ResponseClassifier.Default): ServiceIface =
      ServiceIface(
        findOperationList = ThriftServiceIface(self.FindOperationList, binaryService, pf, stats, responseClassifier))
  }

  class MethodIface(serviceIface: BaseServiceIface)
    extends WorkService[Future] {
    def findOperationList(): Future[Seq[thrift.Operation]] =
      serviceIface.findOperationList(self.FindOperationList.Args())
  }

  implicit object MethodIfaceBuilder
    extends com.twitter.finagle.thrift.MethodIfaceBuilder[ServiceIface, WorkService[Future]] {
    def newMethodIface(serviceIface: ServiceIface): MethodIface =
      new MethodIface(serviceIface)
  }

  object FindOperationList extends com.twitter.scrooge.ThriftMethod {

    object Args extends ThriftStructCodec3[Args] {
      val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
      val Struct = new TStruct("findOperationList_args")

      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo]()

      lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]

      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Args): Unit = {
      }

      def withoutPassthroughFields(original: Args): Args =
        new Args()

      override def encode(_item: Args, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }

      override def decode(_iprot: TProtocol): Args = {
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false

        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case _ =>
                if (_passthroughFields == null)
                  _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()

        new Args(
          if (_passthroughFields == null)
            NoPassthroughFields
          else
            _passthroughFields.result())
      }

      def apply(): Args =
        new Args()

      def unapply(_item: Args): Boolean = true

    }

    class Args(
      val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftStruct
      with _root_.scala.Product
      with HasThriftStructCodec3[Args]
      with java.io.Serializable {
      import Args._
      def this() = this(
        Map.empty)

      override def write(_oprot: TProtocol): Unit = {
        Args.validate(this)
        _oprot.writeStructBegin(Struct)
        if (_passthroughFields.nonEmpty) {
          _passthroughFields.values.foreach { _.write(_oprot) }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
      }

      def copy(
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields): Args =
        new Args(
          _passthroughFields)

      override def canEqual(other: Any): Boolean = other.isInstanceOf[Args]

      private def _equals(x: Args, y: Args): Boolean =
        x.productArity == y.productArity &&
          x.productIterator.sameElements(y.productIterator)

      override def equals(other: Any): Boolean =
        canEqual(other) &&
          _equals(this, other.asInstanceOf[Args]) &&
          _passthroughFields == other.asInstanceOf[Args]._passthroughFields

      override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)

      override def productArity: Int = 0

      override def productElement(n: Int): Any = n match {
        case _ => throw new IndexOutOfBoundsException(n.toString)
      }

      override def productPrefix: String = "Args"

      def _codec: ThriftStructCodec3[Args] = Args
    }

    type SuccessType = Seq[thrift.Operation]

    object Result extends ThriftStructCodec3[Result] {
      val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
      val Struct = new TStruct("findOperationList_result")
      val SuccessField = new TField("success", TType.LIST, 0)
      val SuccessFieldManifest = implicitly[Manifest[Seq[thrift.Operation]]]

      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
          SuccessField,
          true,
          false,
          SuccessFieldManifest,
          _root_.scala.None,
          _root_.scala.Some(implicitly[Manifest[thrift.Operation]]),
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String],
          None))

      lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]

      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Result): Unit = {
      }

      def withoutPassthroughFields(original: Result): Result =
        new Result(
          success =
            {
              val field = original.success
              field.map { field =>
                field.map { field =>
                  field
                }
              }
            })

      override def encode(_item: Result, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }

      override def decode(_iprot: TProtocol): Result = {
        var success: _root_.scala.Option[Seq[thrift.Operation]] = _root_.scala.None
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false

        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 0 =>
                _field.`type` match {
                  case TType.LIST =>
                    success = _root_.scala.Some(readSuccessValue(_iprot))
                  case _actualType =>
                    val _expectedType = TType.LIST
                    throw new TProtocolException(
                      "Received wrong type for field 'success' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)))
                }
              case _ =>
                if (_passthroughFields == null)
                  _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()

        new Result(
          success,
          if (_passthroughFields == null)
            NoPassthroughFields
          else
            _passthroughFields.result())
      }

      def apply(
        success: _root_.scala.Option[Seq[thrift.Operation]] = _root_.scala.None): Result =
        new Result(
          success)

      def unapply(_item: Result): _root_.scala.Option[_root_.scala.Option[Seq[thrift.Operation]]] = _root_.scala.Some(_item.success)

      @inline private[thrift] def readSuccessValue(_iprot: TProtocol): Seq[thrift.Operation] = {
        val _list = _iprot.readListBegin()
        if (_list.size == 0) {
          _iprot.readListEnd()
          Nil
        } else {
          val _rv = new mutable$ArrayBuffer[thrift.Operation](_list.size)
          var _i = 0
          while (_i < _list.size) {
            _rv += {
              thrift.Operation.getOrUnknown(_iprot.readI32())
            }
            _i += 1
          }
          _iprot.readListEnd()
          _rv
        }
      }

      @inline private def writeSuccessField(success_item: Seq[thrift.Operation], _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(SuccessField)
        writeSuccessValue(success_item, _oprot)
        _oprot.writeFieldEnd()
      }

      @inline private def writeSuccessValue(success_item: Seq[thrift.Operation], _oprot: TProtocol): Unit = {
        _oprot.writeListBegin(new TList(TType.I32, success_item.size))
        success_item match {
          case _: IndexedSeq[_] =>
            var _i = 0
            val _size = success_item.size
            while (_i < _size) {
              val success_item_element = success_item(_i)
              _oprot.writeI32(success_item_element.value)
              _i += 1
            }
          case _ =>
            success_item.foreach { success_item_element =>
              _oprot.writeI32(success_item_element.value)
            }
        }
        _oprot.writeListEnd()
      }

    }

    class Result(
      val success: _root_.scala.Option[Seq[thrift.Operation]],
      val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftResponse[Seq[thrift.Operation]] with ThriftStruct
      with _root_.scala.Product1[Option[Seq[thrift.Operation]]]
      with HasThriftStructCodec3[Result]
      with java.io.Serializable {
      import Result._
      def this(
        success: _root_.scala.Option[Seq[thrift.Operation]] = _root_.scala.None) = this(
        success,
        Map.empty)

      def _1 = success

      def successField: Option[Seq[thrift.Operation]] = success
      def exceptionFields: Iterable[Option[com.twitter.scrooge.ThriftException]] = Seq()

      override def write(_oprot: TProtocol): Unit = {
        Result.validate(this)
        _oprot.writeStructBegin(Struct)
        if (success.isDefined) writeSuccessField(success.get, _oprot)
        if (_passthroughFields.nonEmpty) {
          _passthroughFields.values.foreach { _.write(_oprot) }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
      }

      def copy(
        success: _root_.scala.Option[Seq[thrift.Operation]] = this.success,
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields): Result =
        new Result(
          success,
          _passthroughFields)

      override def canEqual(other: Any): Boolean = other.isInstanceOf[Result]

      private def _equals(x: Result, y: Result): Boolean =
        x.productArity == y.productArity &&
          x.productIterator.sameElements(y.productIterator)

      override def equals(other: Any): Boolean =
        canEqual(other) &&
          _equals(this, other.asInstanceOf[Result]) &&
          _passthroughFields == other.asInstanceOf[Result]._passthroughFields

      override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)

      override def productArity: Int = 1

      override def productElement(n: Int): Any = n match {
        case 0 => this.success
        case _ => throw new IndexOutOfBoundsException(n.toString)
      }

      override def productPrefix: String = "Result"

      def _codec: ThriftStructCodec3[Result] = Result
    }

    val annotations: immutable$Map[String, String] = immutable$Map.empty

    type FunctionType = Function1[Args, Future[Seq[thrift.Operation]]]
    type ServiceType = com.twitter.finagle.Service[Args, Result]

    type ServiceIfaceServiceType = com.twitter.finagle.Service[Args, SuccessType]

    def toServiceIfaceService(f: FunctionType): ServiceIfaceServiceType =
      com.twitter.finagle.Service.mk { args: Args =>
        f(args)
      }

    private[this] val toResult = (res: SuccessType) => Result(Some(res))

    def functionToService(f: FunctionType): ServiceType =
      com.twitter.finagle.Service.mk { args: Args =>
        f(args).map(toResult)
      }

    def serviceToFunction(svc: ServiceType): FunctionType = { args: Args =>
      com.twitter.finagle.thrift.ThriftServiceIface.resultFilter(this).andThen(svc).apply(args)
    }

    val name: String = "findOperationList"
    val serviceName: String = "WorkService"
    val argsCodec = Args
    val responseCodec = Result
    val oneway: Boolean = false
  }

  // Compatibility aliases.
  val findOperationList$args = FindOperationList.Args
  type findOperationList$args = FindOperationList.Args

  val findOperationList$result = FindOperationList.Result
  type findOperationList$result = FindOperationList.Result

  trait FutureIface
    extends WorkService[Future] {

    def findOperationList(): Future[Seq[thrift.Operation]]
  }

  class FinagledClient(
    service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
    protocolFactory: org.apache.thrift.protocol.TProtocolFactory = Protocols.binaryFactory(),
    serviceName: String = "WorkService",
    stats: com.twitter.finagle.stats.StatsReceiver = com.twitter.finagle.stats.NullStatsReceiver,
    responseClassifier: ctfs.ResponseClassifier = ctfs.ResponseClassifier.Default)
    extends WorkService$FinagleClient(
      service,
      protocolFactory,
      serviceName,
      stats,
      responseClassifier)
    with FutureIface {

    def this(
      service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
      protocolFactory: TProtocolFactory,
      serviceName: String,
      stats: com.twitter.finagle.stats.StatsReceiver) = this(service, protocolFactory, serviceName, stats, ctfs.ResponseClassifier.Default)
  }

  class FinagledService(
    iface: FutureIface,
    protocolFactory: org.apache.thrift.protocol.TProtocolFactory)
    extends WorkService$FinagleService(
      iface,
      protocolFactory)
}